import Head from 'next/head'
import Layout from '../components/Layout/layout'
import Home from '../components/Home/home'

export default function App() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Home />
      </Layout>
    </>
  )
}
